# Sklearn Example
Here there is a simple example

In [39]:
from sklearn import tree
import numpy as np
X = [[0, 0], [1, 1], [5, 5]]
Y = [0, 1, 2]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

After being fitted, the model can then be used to predict the class of samples:

In [40]:
clf.predict([[2, 2], [-1, -1], [4, 4]])

array([1, 0, 2])

In [41]:
Y = np.array([[2, 2], [-1, -1], [4, 4]])

In [42]:
Y

array([[ 2,  2],
       [-1, -1],
       [ 4,  4]])

In [43]:
clf.predict_proba([[2, 2], [-1, -1], [4, 4]])

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

predict_proba returns a matrix that the columns are classes and the raws are data points.